# Welcome to Serverless!
service: satisfactory-calculator
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  handler:
    handler: main.handler
    events:
      - httpApi:
          path: /handler
          method: get